// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "product/v1alpha/product.proto" (package "product.v1alpha", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ProductCRUDService } from "./product";
import type { DeleteResponse } from "./product";
import type { DeleteRequest } from "./product";
import type { UpdateResponse } from "./product";
import type { UpdateRequest } from "./product";
import type { AddResponse } from "./product";
import type { AddRequest } from "./product";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetResponse } from "./product";
import type { GetRequest } from "./product";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service product.v1alpha.ProductCRUDService
 */
export interface IProductCRUDServiceClient {
    /**
     * @generated from protobuf rpc: Get(product.v1alpha.GetRequest) returns (product.v1alpha.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse>;
    /**
     * @generated from protobuf rpc: Add(product.v1alpha.AddRequest) returns (product.v1alpha.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse>;
    /**
     * @generated from protobuf rpc: Update(product.v1alpha.UpdateRequest) returns (product.v1alpha.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse>;
    /**
     * @generated from protobuf rpc: Delete(product.v1alpha.DeleteRequest) returns (product.v1alpha.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse>;
}
/**
 * @generated from protobuf service product.v1alpha.ProductCRUDService
 */
export class ProductCRUDServiceClient implements IProductCRUDServiceClient, ServiceInfo {
    typeName = ProductCRUDService.typeName;
    methods = ProductCRUDService.methods;
    options = ProductCRUDService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Get(product.v1alpha.GetRequest) returns (product.v1alpha.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRequest, GetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Add(product.v1alpha.AddRequest) returns (product.v1alpha.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddRequest, AddResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Update(product.v1alpha.UpdateRequest) returns (product.v1alpha.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, UpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Delete(product.v1alpha.DeleteRequest) returns (product.v1alpha.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, DeleteResponse>("unary", this._transport, method, opt, input);
    }
}
